# Generated by Django 3.2.10 on 2022-01-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='musicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.TextField()),
                ('title', models.TextField()),
                ('artist', models.TextField()),
                ('tracknumber', models.TextField()),
                ('genre', models.TextField()),
                ('date', models.TextField()),
                ('path', models.TextField()),
            ],
        ),
    ]
